language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.4 RUN_COVER=true
    - RACKET_VERSION=6.5 RUN_COVER=true
    - RACKET_VERSION=6.6 RUN_COVER=true
    - RACKET_VERSION=6.7 RUN_COVER=true
    - RACKET_VERSION=HEAD RUN_COVER=true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - raco pkg install --auto cover cover-codecov

install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR

script:
  - raco test -c compose-app
  - if [ -n "$RUN_COVER" ]; then raco cover -f codecov -d $TRAVIS_BUILD_DIR/coverage -c compose-app compose-app/fancy-app; fi
