language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=5.3.5
    - RACKET_VERSION=5.3.6
    - RACKET_VERSION=6.0
    - RACKET_VERSION=6.0.1
    - RACKET_VERSION=6.1
    - RACKET_VERSION=6.1.1
    - RACKET_VERSION=6.2
    - RACKET_VERSION=6.3
    - RACKET_VERSION=6.4
    - RACKET_VERSION=6.5
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.7
    - RACKET_VERSION=HEAD
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - raco pkg install --auto cover cover-codecov

install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR

script:
  - raco test -c compose-app
  - raco cover -f codecov -d $TRAVIS_BUILD_DIR/coverage -c compose-app compose-app/fancy-app
